export const GET_BEERS = 'GET_BEERS';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SHOW_BEER_DETAILS_MODAL = 'SHOW_BEER_DETAILS_MODAL';
export const HIDE_BEER_DETAILS_MODAL = 'HIDE_BEER_DETAILS_MODAL';
export const BEER_DETAILS_INITIATED = 'BEER_DETAILS_INITIATED';
export const BEER_DETAILS_FETCHING = 'BEER_DETAILS_FETCHING';
export const BEER_DETAILS_FULFILLED = 'BEER_DETAILS_FULFILLED';
